version: '3.8'

services:
  taco:
    build: .
    volumes:
      - .:/app
      - ./coco:/app/coco
      - ./checkpoint:/app/checkpoint
    ports:
      - "8888:8888"
    shm_size: '8gb'
    tty: true
    stdin_open: true
    environment:
      - PYTHONPATH=/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
